#ifndef FLEX_HEADER_EffectLexer_h
#define FLEX_HEADER_EffectLexer_h
#define YY_EffectLexer_CHAR char
#line 1 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Tools\\flex++bison++\\flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 2 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_IOSTREAM 
#line 3 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_LEX_PARAM  YY_EffectParserBase_STYPE *val, YY_EffectParserBase_LTYPE *loc
#line 5 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_MEMBERS  public: UInt m_line; UInt m_column; private: std::ifstream& m_file;
#line 7 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_CONSTRUCTOR_PARAM  std::ifstream& file
#line 9 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_CONSTRUCTOR_INIT  : m_line(1), m_column(1), m_file(file)
#line 11 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#define YY_EffectLexer_IFILE_DEFAULT  &m_file
#line 14 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"

//Code copied to the header file
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include "Core/BasicTypes.h"
#include "Core/Debug.h"
#include "Renderer/EffectSyntaxTreeNodeTypes.h"
#include "EffectParserBase.h"
#include <malloc.h>
#define alloca _alloca

#line 47 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#line 52 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Tools\\flex++bison++\\flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_EffectLexer_IOSTREAM
#include <iostream>
#define YY_EffectLexer_IFILE  std::istream
#define YY_EffectLexer_OFILE std::ostream 
#define YY_EffectLexer_ERRFILE std::cerr

#ifndef YY_EffectLexer_IFILE_DEFAULT
#define YY_EffectLexer_IFILE_DEFAULT &std::cin
#endif

#ifndef YY_EffectLexer_OFILE_DEFAULT
#define YY_EffectLexer_OFILE_DEFAULT &std::cout
#endif

#endif
#endif

#ifndef YY_EffectLexer_IFILE
#define YY_EffectLexer_IFILE FILE 
#endif

#ifndef YY_EffectLexer_OFILE
#define YY_EffectLexer_OFILE FILE 
#endif

#ifndef YY_EffectLexer_ERRFILE
#define YY_EffectLexer_ERRFILE stderr
#endif

#ifndef YY_EffectLexer_IFILE_DEFAULT
#define YY_EffectLexer_IFILE_DEFAULT stdin
#endif

#ifndef YY_EffectLexer_OFILE_DEFAULT
#define YY_EffectLexer_OFILE_DEFAULT stdout
#endif




#ifndef YY_EffectLexer_TEXT
#define YY_EffectLexer_TEXT yytext
#endif
#ifndef YY_EffectLexer_LENG
#define YY_EffectLexer_LENG yyleng
#endif
#ifndef YY_EffectLexer_IN
#define YY_EffectLexer_IN yyin
#endif
#ifndef YY_EffectLexer_OUT
#define YY_EffectLexer_OUT yyout
#endif

#ifndef YY_EffectLexer_LEX_RETURN
#define YY_EffectLexer_LEX_RETURN int
#else
#ifndef YY_EffectLexer_LEX_DEFINED
#define YY_EffectLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_EffectLexer_LEX
#define YY_EffectLexer_LEX yylex
#else
#ifndef YY_EffectLexer_LEX_DEFINED
#define YY_EffectLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_EffectLexer_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_EffectLexer_LEX_PARAM 
#else
#define YY_EffectLexer_LEX_PARAM void
#endif
#else
#ifndef YY_EffectLexer_LEX_DEFINED
#define YY_EffectLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_EffectLexer_LEX_PARAM_DEF
#define YY_EffectLexer_LEX_PARAM_DEF
#else
#ifndef YY_EffectLexer_LEX_DEFINED
#define YY_EffectLexer_LEX_DEFINED 
#endif
#endif

#ifndef YY_EffectLexer_RESTART
#define YY_EffectLexer_RESTART yyrestart
#endif
#ifndef YY_EffectLexer_SWITCH_TO_BUFFER
#define YY_EffectLexer_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_EffectLexer_LOAD_BUFFER_STATE
#define YY_EffectLexer_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_EffectLexer_CREATE_BUFFER
#define YY_EffectLexer_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_EffectLexer_DELETE_BUFFER
#define YY_EffectLexer_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_EffectLexer_INIT_BUFFER
#define YY_EffectLexer_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_EffectLexer_FLEX_DEBUG
#ifndef YY_EffectLexer_DEBUG
#define YY_EffectLexer_DEBUG 1
#endif
#else
#ifndef YY_EffectLexer_DEBUG
#define YY_EffectLexer_DEBUG 0
#endif
#endif

#if YY_EffectLexer_DEBUG != 0
#ifndef YY_EffectLexer_DEBUG_FLAG
#define YY_EffectLexer_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_EffectLexer_DEBUG_INIT
#define YY_EffectLexer_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_EffectLexer_CURRENT_BUFFER
#define YY_EffectLexer_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_EffectLexer_RESTART YY_PROTO(( YY_EffectLexer_IFILE *input_file ));
extern void YY_EffectLexer_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_EffectLexer_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_EffectLexer_CREATE_BUFFER YY_PROTO(( YY_EffectLexer_IFILE *file, int size ));
extern void YY_EffectLexer_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_EffectLexer_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_EffectLexer_IFILE *file ));

#if YY_EffectLexer_DEBUG != 0
extern int YY_EffectLexer_DEBUG_FLAG ;
#endif
extern YY_EffectLexer_CHAR  *YY_EffectLexer_TEXT;
extern int YY_EffectLexer_LENG;
extern YY_EffectLexer_IFILE *YY_EffectLexer_IN;
extern YY_EffectLexer_OFILE *YY_EffectLexer_OUT;
#ifdef YY_EffectLexer_LEX_DEFINED
extern YY_EffectLexer_LEX_RETURN YY_EffectLexer_LEX ( YY_EffectLexer_LEX_PARAM )
YY_EffectLexer_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_EffectLexer_LEX_RETURN YY_EffectLexer_LEX ( YY_EffectLexer_LEX_PARAM )
YY_EffectLexer_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_EffectLexer_CURRENT_BUFFER
#define YY_EffectLexer_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_EffectLexer_CLASS
#define YY_EffectLexer_CLASS EffectLexer
#endif
#ifndef YY_EffectLexer_ECHO
#define YY_EffectLexer_ECHO yy_echo
#endif
#ifdef YY_EffectLexer_ECHO_PURE
#define YY_EffectLexer_ECHO_NOCODE
#endif

#ifndef YY_EffectLexer_ECHO_CODE
#ifndef YY_EffectLexer_IOSTREAM
#define YY_EffectLexer_ECHO_CODE fwrite( (char *) YY_EffectLexer_TEXT, YY_EffectLexer_LENG, 1, YY_EffectLexer_OUT );
#else
#define YY_EffectLexer_ECHO_CODE (YY_EffectLexer_OUT->write( (char *) YY_EffectLexer_TEXT, YY_EffectLexer_LENG));
#endif
#endif

#ifndef YY_EffectLexer_INPUT
#define YY_EffectLexer_INPUT yy_input
#endif
#ifdef YY_EffectLexer_INPUT_PURE
#define YY_EffectLexer_INPUT_NOCODE
#endif

#ifndef YY_EffectLexer_INPUT_CODE
#ifndef YY_EffectLexer_IOSTREAM
#define YY_EffectLexer_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_EffectLexer_IN );
#else
#define YY_EffectLexer_INPUT_CODE if(YY_EffectLexer_IN->eof())  result=0;else {YY_EffectLexer_IN->read(buffer,max_size);result=YY_EffectLexer_IN->gcount();YY_EffectLexer_IN->clear(YY_EffectLexer_IN->rdstate()&(~ios::failbit));if(YY_EffectLexer_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_EffectLexer_FATAL_ERROR_PURE
#define YY_EffectLexer_FATAL_ERRO_NOCODE
#endif
#ifndef YY_EffectLexer_FATAL_ERROR
#define YY_EffectLexer_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_EffectLexer_FATAL_ERROR_CODE
#ifndef YY_EffectLexer_IOSTREAM
#define YY_EffectLexer_FATAL_ERROR_CODE fputs( msg, YY_EffectLexer_ERRFILE );putc( '\n', YY_EffectLexer_ERRFILE );exit( 1 );
#else
#define YY_EffectLexer_FATAL_ERROR_CODE YY_EffectLexer_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_EffectLexer_WRAP
#define YY_EffectLexer_WRAP yy_wrap
#endif
#ifdef YY_EffectLexer_WRAP_PURE
#define YY_EffectLexer_WRAP_NOCODE
#endif
#ifndef YY_EffectLexer_WRAP_CODE
#define YY_EffectLexer_WRAP_CODE return 1;
#endif


#ifndef YY_EffectLexer_INHERIT
#define YY_EffectLexer_INHERIT
#endif
#ifndef YY_EffectLexer_MEMBERS
#define YY_EffectLexer_MEMBERS 
#endif
#ifndef YY_EffectLexer_CONSTRUCTOR_PARAM
#define YY_EffectLexer_CONSTRUCTOR_PARAM
#endif
#ifndef YY_EffectLexer_CONSTRUCTOR_CODE
#define YY_EffectLexer_CONSTRUCTOR_CODE
#endif
#ifndef YY_EffectLexer_CONSTRUCTOR_INIT
#define YY_EffectLexer_CONSTRUCTOR_INIT
#endif
#ifndef YY_EffectLexer_DESTRUCTOR_CODE
#define YY_EffectLexer_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_EffectLexer_CLASS YY_EffectLexer_INHERIT
{
 private:/* data */
 YY_EffectLexer_CHAR  *yy_c_buf_p;
 YY_EffectLexer_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_EffectLexer_CHAR  c, YY_EffectLexer_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_EffectLexer_CURRENT_BUFFER;
 void YY_EffectLexer_RESTART ( YY_EffectLexer_IFILE *input_file );
 void YY_EffectLexer_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_EffectLexer_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_EffectLexer_CREATE_BUFFER( YY_EffectLexer_IFILE *file, int size );
 void YY_EffectLexer_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_EffectLexer_INIT_BUFFER( YY_BUFFER_STATE b, YY_EffectLexer_IFILE *file );
 protected: /* virtual */
 virtual void YY_EffectLexer_ECHO()
#ifdef YY_EffectLexer_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_EffectLexer_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_EffectLexer_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_EffectLexer_FATAL_ERROR(char *msg)
#ifdef YY_EffectLexer_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_EffectLexer_WRAP()
#ifdef YY_EffectLexer_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_EffectLexer_CHAR  *YY_EffectLexer_TEXT;
 int YY_EffectLexer_LENG;
 YY_EffectLexer_IFILE *YY_EffectLexer_IN;
 YY_EffectLexer_OFILE *YY_EffectLexer_OUT;
 YY_EffectLexer_LEX_RETURN YY_EffectLexer_LEX ( YY_EffectLexer_LEX_PARAM);
 YY_EffectLexer_CLASS(YY_EffectLexer_CONSTRUCTOR_PARAM) ;
 virtual ~YY_EffectLexer_CLASS() ;
#if YY_EffectLexer_DEBUG != 0
 int YY_EffectLexer_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_EffectLexer_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 265 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Source\\Renderer\\Grammar\\EffectLexer.l"
#endif
#line 375 "c:\\Documents and Settings\\Bryan\\My Documents\\PerforceWorkspace\\OidFX\\Tools\\flex++bison++\\flexskel.h"

/* end of generated header */
